### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by alanjames1987** [sindresorhus/chalk#50]
Does Chalk run in a browser? If not are there plans to get it running in a browser with something like Browserify?

**Comment by SBoudrias** [comment]
Check https://github.com/sindresorhus/chalk/issues?q=is%3Aissue+browser+is%3Aclosed

**Comment by jbnicolai** [comment]
@SBoudrias thanks for looking up the previous issues!

@alanjames1987 thia module concerns itself with `tty` command-line interface escape codes for coloring.

**Comment by alanjames1987** [comment]
@jbnicolai That makes sense. Thanks for explaining.

**Comment by AntouanK** [comment]
@alanjames1987 @jbnicolai @SBoudrias 
Try [consologger](https://www.npmjs.com/package/consologger) if you want. Let me know your feedback.
