### ISSUE TITLE
supportsColor

### ISSUE THREAD

**Issue by JSteunou** [sindresorhus/chalk#51]
chalk.supportsColor is on false whereas package supports-color installed in global and run from command line says true.

Ubuntu 14.10 default gnome terminal & guake.

**Comment by sindresorhus** [comment]
The the programmatic version of `supports-color` also `false`? https://github.com/sindresorhus/supports-color#usage

Can you try checking which check it returns on https://github.com/sindresorhus/supports-color/blob/master/index.js ?

**Comment by JSteunou** [comment]
Like I said, package `supports-color` return true.

```
supports-color@1.2.0 /usr/lib/node_modules/supports-color
$ node
> var sc = require('supports-color');
undefined
> sc
true
> 
```

```
> process.env.TERM
xterm
```

But chalk.supportsColor (used in a sequelize migrate script) is false because of `process.stdout && !process.stdout.isTTY`

Moreover chalk use 0.x of supports-color instead of 1.x

**Comment by sindresorhus** [comment]
> But chalk.supportsColor (used in a sequelize migrate script) is false because of process.stdout && !process.stdout.isTTY

Then it has nothing to do with the difference of running the CLI vs the API.

Most people don't want colors when their script is piped, if you do however, you can force it with the CLI flag: `--color`.

**Comment by JSteunou** [comment]
So it has to do with the fact my js script is launch by another script?

**Comment by sindresorhus** [comment]
Yes

**Comment by JSteunou** [comment]
Ok, thank you @sindresorhus

**Comment by sindresorhus** [comment]
@JSteunou Can you put `console.log(process.env, process.argv);` in your script and share the output? Curious if sequelize adds anything I can use to detect it.

**Comment by JSteunou** [comment]
process.env (I trimmed all non relevant information)

```
 _: '/usr/bin/sequelize' 
```

process.argv

```
  'node',
  '/usr/lib/node_modules/sequelize-cli/node_modules/sequelize/bin/sequelize.js',
  'db:migrate',
  '--sequelizefile',
  '/usr/lib/node_modules/sequelize-cli/lib/sequelizefile.js',
  '--cwd',
  '/my/cwd' 
```

**Comment by sindresorhus** [comment]
Hmm, yeah, doesn't look like anything I can use reliably. Thanks anyways :)

**Comment by JSteunou** [comment]
no problem ;)
