### ISSUE TITLE
(Windows) Consider using standard color scheme when term is xterm like

### ISSUE THREAD

**Issue by weikinhuang** [sindresorhus/chalk#59]
perhaps check for:

`process.platform === 'win32' && !process.env.TERM`
or
`process.platform === 'win32' && !(/xterm/).test(process.env.TERM || "")`

I am suggesting this because I use node through a solarized color shell (admittedly through cygwin ssh).

Thanks.

**Comment by shinnn** [comment]
@weikinhuang Why current version doesn't meet your requirements? Current / expected screenshot is very welcome.

**Comment by weikinhuang** [comment]
Sure thing, here's the screenshot (using SecureCRT, with xterm-256 emulator mode):

![image](https://cloud.githubusercontent.com/assets/794658/7144950/dd66e196-e2b6-11e4-9926-5fbcb4487bc0.png)


```javascript
"use strict";

const chalk = require("chalk");

[ "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white", "gray" ].forEach(function(color) {
	process.stdout.write(chalk[color](color) + " ");
});
process.stdout.write("\n");

[ "bgBlack", "bgRed", "bgGreen", "bgYellow", "bgBlue", "bgMagenta", "bgCyan", "bgWhite" ].forEach(function(color) {
	process.stdout.write(chalk[color](color) + " ");
});
process.stdout.write("\n");
```

**Comment by shinnn** [comment]
I say again:

> Why current version doesn't meet your requirements?

The screenshot looks good to me.

**Comment by weikinhuang** [comment]
Ah, sorry.
Since I'm on a xterm console (instead of `cmd` or something) I expect that blue would show up as blue and not a grey color even though I'm on windows.

The following would be the expected behavior:
![image](https://cloud.githubusercontent.com/assets/794658/7146612/b2303d72-e2c2-11e4-9e06-3b29d0b321ef.png)

**Comment by shinnn** [comment]
Ah, OK. You meant that chalk should disable [these lines](https://github.com/sindresorhus/chalk/blob/04cb2d21ae59037efe0db1d8418cb5662e09bead/index.js#L14-L17) on the terminals with solarized color theme?

**Comment by weikinhuang** [comment]
Ya, but not necessarily with a solarized theme, but terminals that supports proper colors.

**Comment by kevva** [comment]
Can you send a PR?

**Comment by weikinhuang** [comment]
PR sent, I couldn't decide if I should test against `xterm` or `dumb` terminal (that's what `cmd.exe` reports in `process.env.TERM`).
