### ISSUE TITLE
chalk.reset doesn't work?

### ISSUE THREAD

**Issue by cheahkhing** [sindresorhus/chalk#62]
Hi, I tried to use chalk.reset() to reset my formatted string, but somehow the color is still applied and doesn't get removed.
Is this intended?

**Comment by shinnn** [comment]
You meant [`chalk.stripColor`](https://github.com/sindresorhus/chalk#chalkstripcolorstring)? I cannot find `chalk.reset` in [the code](https://github.com/sindresorhus/chalk/blob/master/index.js).

And a sample code that can reproduce the problem is very welcome.

**Comment by shinnn** [comment]
Ah, sorry chalk actually has `reset` method.

**Comment by shinnn** [comment]
OK I found the cause. You're trying to strip colors with `chalk.reset()` but that's wrong. [ANSI `reset` code](http://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes) only removes graphic renditions such as `bold` and `italic`. 

Use  [`chalk.stripColor`](https://github.com/sindresorhus/chalk#chalkstripcolorstring) for your purpose.

**Comment by sindresorhus** [comment]
https://github.com/chalk/strip-ansi
