### ISSUE TITLE
README screenshot doesn't show strikethrough correctly

### ISSUE THREAD

**Issue by rosswilson** [sindresorhus/chalk#65]
I know that strikethrough isn't widely supported, but shouldn't the README screenshot (https://raw.githubusercontent.com/sindresorhus/ansi-styles/master/screenshot.png) show strikethough working?

**Comment by sindresorhus** [comment]
Nah, doesn't matter. The current screenshot is more realistic of what you can expect. You shouldn't use `strikethrough`.
