### ISSUE TITLE
Having less dependencies

### ISSUE THREAD

**Issue by Raynos** [sindresorhus/chalk#69]
When i was importing `chalk` into a module of mine to add colors I was suprised it added 9 modules to my dependency tree.

This seems quite expensive for a simple feature.

To work around this I created a "fork" ( https://github.com/Raynos/term-color#motivation ) with less features. 

I'm not sure if chalk is interested in having less dependencies. This would allow me to deprecate my fork but might go against what chalk is as it means removing features.

**Comment by jbnicolai** [comment]
> This seems quite expensive for a simple feature

> `term-color` adds colors to your library but only costs 3 dependencies instead of costing 9 dependencies.


But what makes it *actually* expensive? There's not some price you pay per dependency. The download time depends on the *size* of all installed packages, which I assure you are I quite small, and the run-time performance depends on the implementation - which is pretty optimized. Hell, one of the dependencies, [`escape-string-regexp`](https://github.com/sindresorhus/escape-string-regexp/blob/master/index.js) is only ten lines in its entirety.

**Comment by Raynos** [comment]
Fair enough. This is not something that matters for chalk.

**Comment by sindresorhus** [comment]
@Raynos I want to understand why it matters for you? The total size of `chalk` is 50 KB, while `term-color` is 26 KB. I don't really see the big difference. 

With npm@3 all dependencies are going to be deduped by default, so this is going to be a non-issue soon. I actually would like to remove the `has-ansi` and `strip-ansi` dependencies as I never use them and users could just require them if needed, but that's not going to happen until chalk 3.0.0 if at all, as a lot of people depend on those.

**Comment by jbnicolai** [comment]
@sindresorhus +1 on removing the bundled `has-ansi` and `strip-ansi` for v3.

**Comment by sindresorhus** [comment]
Ok, let's: https://github.com/sindresorhus/chalk/issues/70
